version: '3.12'

services:

  web:
    build: .
    command: tail -f /dev/null
    image: frontend
    volumes:
      - .:/frontend
    env_file:
      - ./.env
    ports:
      - 5173:5173
    container_name: frontend
