version: '3.12'

services:

  web:
    build: .
    command: npm run dev
    image: frontend
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - 5173:5173
    container_name: frontend
