version: '3.12'

services:

  web:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/backend
    env_file:
      - ./.env
    environment:
      - MYSQL_HOST=disaXta.db
    ports:
      - 8000:8000
    container_name: disaXta.web
    depends_on:
      - db

  db:
    image: mysql
    env_file:
      - ./.env
    ports:
      - 3306:3306
    container_name: disaXta.db
    volumes:
      - mysql_data:/var/lib/mysql
  
volumes:
  mysql_data:

