version: '3.12'

services:

  web:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/backend
    env_file:
      - ./.env
    environment:
      - MYSQL_HOST=backend.db
    ports:
      - 8000:8000
    container_name: backend.web
    depends_on:
      - db

  db:
    image: mysql
    env_file:
      - ./.env
    ports:
      - 3307:3306
    container_name: backend.db
    volumes:
      - mysql_data:/var/lib/mysql
  
volumes:
  mysql_data:
    name: "disaXta-data"

