version: '3'

services:
  chatbot:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: masterjoe
      MYSQL_DATABASE: post
      MYSQL_USER: masterjoe
      MYSQL_PASSWORD: masterjoe
    volumes:
      - ./mariadb-data:/var/lib/mysql  # Use a volume to persist MariaDB data
