version: '3.12'

services:

  web:
    build: .
    command: tail -f /dev/null
    image: oauth
    volumes:
      - .:/oauth
      - node_modules:/oauth/node_modules
      - .env:/oauth/.env
    env_file:
      - ./.env
    ports:
      - 3000:3000
    container_name: oauth.web
    depends_on:
      - db

  db:
    image: mysql
    env_file:
      - ./.env
    ports:
      - 3306:3306
    container_name: oauth.db
    volumes:
      - mysql_data:/var/lib/mysql
  
volumes:
  mysql_data:
    name: "oauth-data"
  node_modules:
  .env:

